### ISSUE TITLE
The 'singer-python==1.5.0' distribution was not found and is required by target-gsheet

### ISSUE THREAD

**Issue by dejavoodooo** [singer-io/target-gsheet#9]
Having some dependency issues with using target-gsheet and tap-ringcentral together. Due to tap-framework, dependency issues are causing a problem between the two.

**Comment by luandy64** [comment]
Did you install the tap in a separate virtual environment from the target?

**Comment by dejavoodooo** [comment]
After making this post I realized that is how tap was originally designed. To work in separate environments and some tools requiring different dependencies. Sorry for the bother.

**Comment by luandy64** [comment]
I'm glad you were able to solve the problem for yourself 👍 

Please close this issue if you don't have any other questions.
